import Head from 'next/head';

// import CommonLayout from '@/components/CommonLayout';
// import Rules from '@/components/Rules';
import CommonLayout from '../../components/CommonLayout';
import Rules from '../../components/Rules';

export default function RulesSection() {
  return (
    <>
      <Head>
        <title>Правдивые отзывы.ру</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonLayout>
        <main>
          <Rules />
        </main>
      </CommonLayout>
    </>
  );
}
