import Head from 'next/head';
import { useRouter } from 'next/router';

import CommonLayout from '@/components/CommonLayout';
import Main from '@/components/Main';

import ReviewCard from '@/components/Reviews/ReviewCard';
import { reviews } from '@/common/reviews/reviews';
import { useEffect, useState } from 'react';

export default function ReviewPage() {
  const router = useRouter();
  const { id } = router.query;

  const [review, setReview] = useState({});

  useEffect(() => {
    setReview(reviews.find((item) => item.id == id));
  }, []);

  return (
    <>
      <Head>
        <title>Правдивые отзывы.ру</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonLayout>
        <main>
          <Main />
          {review && <ReviewCard {...review} />}
        </main>
      </CommonLayout>
    </>
  );
}
