import Head from 'next/head';

import CommonLayout from '@/components/CommonLayout';
import Main from '@/components/Main';
import Reviews from '@/components/Reviews';

import { reviews } from '@/common/reviews/reviews';
import { useState, useEffect } from 'react';

export default function Home() {
  const [rating, setRating] = useState(null);
  const [reviewsToDisplay, setReviewsToDisplay] = useState(reviews);

  useEffect(() => {
    if (rating === null) {
      setReviewsToDisplay(reviews);
    } else {
      setReviewsToDisplay(reviews.filter((item) => item.ratings === rating));
    }
  }, [rating]);

  return (
    <>
      <Head>
        <title>Правдивые отзывы.ру</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonLayout>
        <main>
          <Main setRating={setRating} />
          <Reviews reviews={reviewsToDisplay} />
        </main>
      </CommonLayout>
    </>
  );
}
